// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_label1 = lv_label_create(ui_mainScreen);
    lv_label_set_text(ui_label1, "Hello, this is lvgl v8.3.6 running on with esp32.");
    lv_label_set_long_mode(ui_label1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_center(ui_label1);
    lv_obj_set_width(ui_label1, 300);
}
